/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "teuznyweetzxctpjhghq"
export const publicAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY || "sb_publishable_4L5dZN_8PaD8z8CAwx6rRw_EsbT07kV"
export const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || `https://${projectId}.supabase.co`